### ISSUE TITLE
Docker compose implementation

### ISSUE THREAD

**Issue by xBounceIT** [netzbegruenung/keycloak-scriptmapper-ldap-id#2]
Hi,

thanks for your work. I am having the exact same issue in implementing the ldap_id with nextcloud.

I have created the following dockerfile based on the Keycloak documentation and added your jar into providers folder.

```
FROM quay.io/keycloak/keycloak:25.0.2 as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

ENV KC_DB=postgres

WORKDIR /opt/keycloak

COPY ldap-id-uppercase.jar /opt/keycloak/providers/ldap-id-uppercase.jar

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:25.0.2
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]

```

Then, i have created this docker compose enabling the scripts feature:

```
services:
  postgres:
    image: postgres:REDACTED
    container_name: iam_db
    hostname: iam_db
    restart: unless-stopped
    volumes:
      - REDACTED:REDACTED
    environment:
      TZ: Europe/Rome
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - REDACTED

  keycloak:
    image: REDACTED/keycloak:25.0.2
    container_name: iam
    hostname: iam
    restart: unless-stopped
    command: start
    environment:
      TZ: Europe/Rome
      KC_HOSTNAME: REDACTED
      KC_HOSTNAME_PORT: REDACTED
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HTTPS_CERTIFICATE_FILE: REDACTED
      KC_HTTPS_CERTIFICATE_KEY_FILE: REDACTED
      KC_FEATURES: "scripts"
    ports:
      - REDACTED:REDACTED
    depends_on:
      - postgres
    networks:
      - REDACTED
    volumes:
      - REDACTED


volumes:
  REDACTED:
```

After all this i head to the mapper config inside the profile scope but the ldap_id_uppercase mapper is missing for some reason.

![immagine](https://github.com/user-attachments/assets/50d6bcab-c39b-4cb5-8c87-10fc084ad618)

Am i missing something?
